tests:
  "Pages should be fast enough":
    path: "/.*" # run the assertions for all HTTP requests
    assertions:
      - "main.wall_time < 200ms" # wall clock time is less than 100ms

scenarios: |
  #!blackfire-player

  scenario
      name "Test health of homepage"
      visit url('/')
          expect status_code() == 200