metrics:
  app.user_activity_calculation:
    label: "User activity calculation"
    timeline: true
    marker: true
    matching_calls:
      php:
        - callee: '=App\Service\CommentHelper::countRecentCommentsForUser'

  app.agree_to_terms:
    label: "Agree to terms"
    matching_calls:
      php:
        - caller: '=App\EventSubscriber\AgreeToTermsSubscriber::onRequestEvent'
          callee: '|Symfony\Component\Form\FormFactoryInterface::create'

tests:
  "The homepage should be fast":
    path: "/"
    assertions:
      - "main.wall_time < 100ms"

  "The homepage should have a limited number of SQL queries":
    path: "/"
    assertions:
      - "metrics.sql.queries.count <= 5"

  "The number of created entities should be reasonable":
    path: "/.*"
    assertions:
      - "metrics.entities.created.count < 50"

  "The autoloader classmap should be dumped":
    path: "/.*"
    assertions:
      - "metrics.composer.autoload.find_file.count == 0"

  "User activity calculation should be cached":
    path: "/sighting/.*"
    assertions:
      - "metrics.app.user_activity_calculation.count == 0"

  "User should already have agreed to terms":
    path: "/.*"
    assertions:
      - "metrics.app.agree_to_terms.count == 0"

  "Github API should never be called after first load (cached)":
    path: "/api/github-organization"
    assertions:
      - "metrics.http.requests.count == 0"